<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-01T19:09:30 IST" name="Suite" finished-at="2024-05-01T19:09:57 IST" duration-ms="27072">
    <groups>
    </groups>
    <test started-at="2024-05-01T19:09:30 IST" name="Test" finished-at="2024-05-01T19:09:57 IST" duration-ms="27072">
      <class name="main.endToEnd">
        <test-method is-config="true" signature="configureAppium()[pri:0, instance:main.endToEnd@5b6ec132]" started-at="2024-05-01T19:09:30 IST" name="configureAppium" finished-at="2024-05-01T19:09:36 IST" duration-ms="5298" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- configureAppium -->
        <test-method signature="fillForm()[pri:0, instance:main.endToEnd@5b6ec132]" started-at="2024-05-01T19:09:36 IST" name="fillForm" finished-at="2024-05-01T19:09:56 IST" duration-ms="20577" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [131.0] but found [270.97]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [131.0] but found [270.97]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEquals(Assert.java:701)
at org.testng.Assert.assertEquals(Assert.java:712)
at main.endToEnd.fillForm(endToEnd.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fillForm -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:main.endToEnd@5b6ec132]" started-at="2024-05-01T19:09:57 IST" name="tearDown" finished-at="2024-05-01T19:09:57 IST" duration-ms="402" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- main.endToEnd -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
